# Generated by Django 5.1.4 on 2024-12-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(default="Headshot.jpg", upload_to="profile-image"),
        ),
    ]
