# Generated by Django 5.1.4 on 2024-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="static/images/Headshot.jpg", upload_to="profile-image"
            ),
        ),
    ]
