# Generated by Django 5.1.4 on 2025-01-04 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="accounts.Contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
