# Generated by Django 5.1.4 on 2025-01-03 11:14

import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_likes"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="blog",
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="publish",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
